<a href="https://colab.research.google.com/github/eunsu12/DALC_Scalar/blob/main/K_MOOC_2.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# **01 데이터 구조와 Numpy 기초**
## **프로그래밍 언어**
### R: 통계를 위한 , Python: 연산을 위한 오픈소스 라이브러리 -> 유연성 (Numpy, Pandas, Scipy, Matplotlib, Scikit-Learn
## **넘파이** -> import numpy as np
* array 단위로 데이터 관리 및 연산 수행 
*  복소수 데이터 타입도 표현 가능


> ### **배열 슬라이싱** x[start:stop:step]
>> #### 기본값:   start=0 , stop은 차원의 크기,  step=1
> ### **배열 결합 :  concantenate,vstack(수직스택),hstack(수평스택)**
> ### **배열 분할 : split, vsplit, hsplit** 
>> split(분할 대상 리스트, 분할 위치), hsplit( , [2])->  좌우 2개로 나눔


In [ ]:
import numpy as np

In [ ]:
 # array 정의와 사용방법
 data1 = [1,2,3,4,5]
 data2=[6,5,4,3,2,1]
 print(data1,data2)

[1, 2, 3, 4, 5] [6, 5, 4, 3, 2, 1]


In [ ]:
ar1 = np.array(data1)
ar1

array([1, 2, 3, 4, 5])

In [ ]:
# 데이터 타입 dtype
ar2= np.array(data1, dtype= 'float32')
ar2

array([1., 2., 3., 4., 5.], dtype=float32)

In [ ]:
# 5X3행렬(1에서 4전 2에서 5전 ...)
ar3= np.array([range(i,i+3) for i in data1])
ar3

array([[1, 2, 3],
       [2, 3, 4],
       [3, 4, 5],
       [4, 5, 6],
       [5, 6, 7]])

In [ ]:
# full((행렬크기), 지정값)
ar4=np.full((3,5),3.14)
ar4

array([[3.14, 3.14, 3.14, 3.14, 3.14],
       [3.14, 3.14, 3.14, 3.14, 3.14],
       [3.14, 3.14, 3.14, 3.14, 3.14]])

In [ ]:
#range()와 유사
ar5 = np.arange(0,20,2)
ar5             

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18])

In [ ]:
#앞 2개의 값 사이에 3개 요소값을 가진 배열 생성
ar6=np.linspace(0,1,3) 
ar6

array([0. , 0.5, 1. ])

In [ ]:
#3X3 0~1 사이의 무작위 값
ar7= np.random.random((3,3))
ar7

array([[0.56288364, 0.83287358, 0.5499009 ],
       [0.57924296, 0.24440918, 0.33942448],
       [0.74336731, 0.49091611, 0.63545336]])

In [ ]:
#0~100 사이 3X3
ar8= np.random.randint(0,100,(3,3))
ar8

array([[94, 10, 55],
       [ 9, 33, 15],
       [59, 86, 42]])

In [ ]:
#3X3의 단위행렬
ar9=np.eye(3)
ar9

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [ ]:
x=np.random.randint(10,size=(3,4,5))
x

array([[[8, 3, 6, 1, 9],
        [1, 0, 2, 4, 7],
        [9, 1, 6, 8, 9],
        [9, 5, 2, 6, 6]],

       [[4, 4, 1, 0, 0],
        [6, 7, 2, 2, 3],
        [9, 5, 4, 9, 4],
        [9, 5, 2, 5, 3]],

       [[0, 1, 5, 4, 1],
        [6, 7, 8, 1, 4],
        [9, 7, 3, 3, 5],
        [7, 5, 7, 6, 9]]])

In [ ]:
print('차원의 개수',x.ndim)
print('차원의 크기',x.shape)
print('전체 배열 크기', x.size)

차원의 개수 3
차원의 크기 (3, 4, 5)
전체 배열 크기 60


In [ ]:
y=np.array([2,4,6,8,10])
print(y[0],y[-2])

2 8


In [ ]:
z=np.array([[2,4,6,8,10],[3,6,9,12,15]])
print(z[1,0])
z[0,0]=12
print(z)

3
[[12  4  6  8 10]
 [ 3  6  9 12 15]]


In [ ]:
x=np.arange(10)
x[4:8],x[:5],x[5:]

(array([4, 5, 6, 7]), array([0, 1, 2, 3, 4]), array([5, 6, 7, 8, 9]))

In [ ]:
z=np.array([[2,4,6,8],[3,6,9,12],[4,8,12,16]])
#0,1행 0,1,2열
print(z[:2,:3])
#0,1,2행 , 0,2열
print( z[:3,::2])

[[2 4 6]
 [3 6 9]]
[[ 2  6]
 [ 3  9]
 [ 4 12]]


In [ ]:
z=np.arange(1,10).reshape(3,3)
z

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [ ]:
x=np.array([1,2,3])
y=np.array([3,2,1])
z=np.concatenate([x,y])
z

array([1, 2, 3, 3, 2, 1])

In [ ]:
x=np.array([1,2,3])
grid=np.array([[4,5,6],[7,8,9]])
v=np.vstack([x,grid])
v

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [ ]:
y=np.array([[99],[99]])
z=np.hstack([grid,y])
z

array([[ 4,  5,  6, 99],
       [ 7,  8,  9, 99]])

# **02 Numpy 심화**
## 단항 유니버설 함수

*   abs() -> 복소수 가능
*   sin() cos() tan()
*   arcsin arccos arctan :역삼각함수
*   exp , exp2 ,power(3,x) : 지수함수
*   log log2 log10 : 로그함수
*   np. multiply(x,10,out=y) -> 직접 연산 결과 표시 가능 y[::2] 가능 --> 대규모 연산 시간, 메모리 절약

> ## 집계함수
>>### np.add.reduce(x)   ---> 결과가 하나만 남을 때까지 add를 반복적으로 적용
>>### sum,max,min --->axis=0 열별 axis=1 행별

>## 브로드캐스팅 연산
>>### 서로 다른 크기의 배열에 이항 유니버설 함수를 적용
>>### 브로드캐스팅에 의해 1차원으로 확장

###비교 연산자와 유니버설 함수
### == np.equal

>sort 함수
>> np.sort() , x.sort()
>> np. argsort() 정렬된 요소의 인덱스 반환
>> x_reverse = np.sort(x)[::-1] ---> 내림차순 정렬
>>> axis=0 열기준 작은 것부터 정렬 axis=1 행기준 작은 것부터 원소 정렬










