<a href="https://colab.research.google.com/github/eunsu12/DALC_Scalar/blob/main/K_MOOC_3%2C4.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

#**3-1 Pandas 데이터 가공하기**
### Series   
### pd.Series(data,index=index)       
-  data:리스트 혹은 Numpy 배열,index:생략가능 (정수일 필요 없음 어떤 타입으로도 가능)
- data가 딕셔너리일 경우 요소 입력 순서로 출력된다 -> 그냥 딕셔너리는 키 정렬

### DataFrame
### pd.DataFrame(data,index=index,columns=columns)       

In [1]:
import numpy as np
import pandas as pd

In [2]:
data = pd.Series([0.25,0.5,0.75,1.0])
data

0    0.25
1    0.50
2    0.75
3    1.00
dtype: float64

In [3]:
data.values, data.index

(array([0.25, 0.5 , 0.75, 1.  ]), RangeIndex(start=0, stop=4, step=1))

In [4]:
#1,2
data[1:3]

1    0.50
2    0.75
dtype: float64

In [9]:
population_dict = {'California':38332521,
                   'Texas':26448393,
                   'New York':19651127,
                   'Florida': 19552860,
                   'lllinois': 12882135}
population = pd.Series(population_dict)
population

California    38332521
Texas         26448393
New York      19651127
Florida       19552860
lllinois      12882135
dtype: int64

In [10]:
population['California': 'lllinois']

California    38332521
Texas         26448393
New York      19651127
Florida       19552860
lllinois      12882135
dtype: int64

In [11]:
pd.Series(5,index=[100,200,300])

100    5
200    5
300    5
dtype: int64

In [12]:
pd.Series({2:'a',1:'b',3:'c'},index=[3,2])

3    c
2    a
dtype: object

In [14]:
area_dict = {'California':423967,
                   'Texas':695662,
                   'New York':141297,
                   'Florida': 170312,
                   'lllinois': 149995}
area = pd.Series(area_dict)
states = pd.DataFrame({'population':population,
                       'area': area})
states

population    area
California    38332521  423967
Texas         26448393  695662
New York      19651127  141297
Florida       19552860  170312
lllinois      12882135  149995

In [15]:
states.index, states.columns

(Index(['California', 'Texas', 'New York', 'Florida', 'lllinois'], dtype='object'),
 Index(['population', 'area'], dtype='object'))

In [16]:
pd.DataFrame(population,columns=['population'])

population
California    38332521
Texas         26448393
New York      19651127
Florida       19552860
lllinois      12882135

In [17]:
pd.DataFrame(population,index=['Texas'],columns=['population'])

population
Texas    26448393

In [18]:
#누락된 자리는 NaN
pd.DataFrame([{'a':1,'b':2},{'b':3,'c':4}])

a  b    c
0  1.0  2  NaN
1  NaN  3  4.0

In [20]:
pd.DataFrame(np.random.rand(3,2),columns=['foo','bar'],index=['a','b','c'])

foo       bar
a  0.766990  0.842389
b  0.394536  0.132079
c  0.951646  0.137003

#**3-2 Pandas 데이터 연산하기**
-  ### ind= pd.index([1,2,3]) : 불변배열 ind[1]->2
-  ### ind.size shape ndim dtype (크기, 모양, 차원, type)
-  ### &, |, ^ 교집합, 합집합, 대칭차
-  ## loc(인덱스 이름), iloc(정수형 위치 인덱스) 
  -  범위의 끝 포함  |   범위의 끝 제외
-  ### + -> add,- -> sub,* -> mul,/ -> div ,NaN -> fill_value=0
  -  student1.add(student2, fill_value=0)

In [22]:
data = pd.Series([0.25,0.5,0.75,1.0], index=['a','b','c','d'])
data.loc['a':'c'] , data.iloc[1:3] 

(a    0.25
 b    0.50
 c    0.75
 dtype: float64, b    0.50
 c    0.75
 dtype: float64)

In [23]:
states['density'] = states['population'] / states['area']
states

population    area     density
California    38332521  423967   90.413926
Texas         26448393  695662   38.019028
New York      19651127  141297  139.076746
Florida       19552860  170312  114.806121
lllinois      12882135  149995   85.883763

In [24]:
states.values

array([[3.83325210e+07, 4.23967000e+05, 9.04139261e+01],
       [2.64483930e+07, 6.95662000e+05, 3.80190279e+01],
       [1.96511270e+07, 1.41297000e+05, 1.39076746e+02],
       [1.95528600e+07, 1.70312000e+05, 1.14806121e+02],
       [1.28821350e+07, 1.49995000e+05, 8.58837628e+01]])

In [25]:
states.T

California         Texas  ...       Florida      lllinois
population  3.833252e+07  2.644839e+07  ...  1.955286e+07  1.288214e+07
area        4.239670e+05  6.956620e+05  ...  1.703120e+05  1.499950e+05
density     9.041393e+01  3.801903e+01  ...  1.148061e+02  8.588376e+01

[3 rows x 5 columns]

In [26]:
#행 접근
states.values[0]

array([3.83325210e+07, 4.23967000e+05, 9.04139261e+01])

In [27]:
#열 접근
states['area']

California    423967
Texas         695662
New York      141297
Florida       170312
lllinois      149995
Name: area, dtype: int64

In [29]:
states.iloc[:3,:2]

population    area
California    38332521  423967
Texas         26448393  695662
New York      19651127  141297

In [30]:
states.loc[:'New York',:'area']

population    area
California    38332521  423967
Texas         26448393  695662
New York      19651127  141297

#**4-1 Pandas 심화(1)**

In [49]:
rc= pd.read_csv('/Users/eunsu/Downloads/일별평균대기오염도_2019.csv', header=None ,encoding='euc-kr')
rc

FileNotFoundError: ignored

#**4-2 Pandas 심화(2)**
###plot() 사용
  -  kind = 'line'  'bar' 'barh' 'hist'  'box' 'scatter' 등 사용가능